### ISSUE TITLE
service printing out sensitive information to the log

### ISSUE THREAD

**Issue by vrockaibrx** [LambdaTest/wdio-lambdatest-service#78]
We're getting errors like this quite often and it's spamming our test logs:
```
[0-52] AxiosError: Request failed with status code 404
[0-52]     at settle (/data/src/node_modules/axios/lib/core/settle.js:19:12)
[0-52]     at BrotliDecompress.handleStreamEnd (/data/src/node_modules/axios/lib/adapters/http.js:589:11)
[0-52]     at BrotliDecompress.emit (node:events:529:35)
[0-52]     at BrotliDecompress.emit (node:domain:489:12)
[0-52]     at endReadableNT (node:internal/streams/readable:1400:12)
[0-52]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-52]     at Axios.request (/data/src/node_modules/axios/lib/core/Axios.js:45:41)
[0-52]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-52]     at updateSessionById (/data/src/node_modules/wdio-lambdatest-service/src/util.js:43:24)
[0-52]     at LambdaRestService.updateJob (/data/src/node_modules/wdio-lambdatest-service/src/service.js:297:7)
[0-52]     at LambdaRestService._update (/data/src/node_modules/wdio-lambdatest-service/src/service.js:284:14)
[0-52]     at LambdaRestService.onReload (/data/src/node_modules/wdio-lambdatest-service/src/service.js:263:7)
[0-52]     at async Promise.all (index 0)
[0-52]     at Browser.reloadSession (/data/src/node_modules/webdriverio/build/commands/browser/reloadSession.js:54:9)
[0-52]     at Browser.wrapCommandFn (/data/src/node_modules/@wdio/utils/build/shim.js:136:29)
```

The problem is that the service prints out the error in the log together with the request data which contains sensitive data in headers:
```
[0-52]   code: 'ERR_BAD_REQUEST',
...
[0-52]     headers: Object [AxiosHeaders] {
[0-52]       Accept: 'application/json',
[0-52]       'Content-Type': 'application/json',
[0-52]       Authorization: 'Basic SENSITIVE DATA',
                                                       ^^^^^^^^^^^^^
[0-52]       'User-Agent': 'axios/1.6.7',
[0-52]       'Content-Length': '112',
[0-52]       'Accept-Encoding': 'gzip, compress, deflate, br'
[0-52]     },
[0-52]     method: 'patch',
[0-52]     url: 'https://api.lambdatest.com/automation/api/v1/sessions/*******************************',
[0-52]     data: '{"name":"Test name","status_ind":"passed"}'
[0-52]   },
```

**Comment by Shahnawaz-Sk** [comment]
sure we will look into this @vrockaibrx

**Comment by Shahnawaz-Sk** [comment]
@vrockaibrx We have fixed it. You now have the option to enable log generation by setting the environment variable `LT_API_LOG=true` and also you can provide custom path using this optional environment variable `LT_API_LOG_FILE`.
