### ISSUE TITLE
Support for WDIO cli @ 9

### ISSUE THREAD

**Issue by badman-rodriguez** [LambdaTest/wdio-lambdatest-service#97]
As soon as I upgraded to v9, I started getting this error:

```
[0-1] 2024-11-11T21:47:03.636Z ERROR @wdio/utils:shim: SyntaxError: Invalid left-hand side in assignment
[0-1]     at new Function (<anonymous>)
[0-1]     at Browser.execute (/app/node_modules/webdriverio/build/index.js:3079:53)
[0-1]     at Browser.wrapCommandFn (/app/node_modules/@wdio/utils/build/index.js:884:23)
[0-1]     at LambdaRestService._executeCommand (/app/node_modules/wdio-lambdatest-service/src/service.js:429:12)
[0-1]     at LambdaRestService._setSessionName (/app/node_modules/wdio-lambdatest-service/src/service.js:416:5)
[0-1]     at LambdaRestService.setSessionName (/app/node_modules/wdio-lambdatest-service/src/service.js:394:7)
[0-1]     at LambdaRestService.beforeSuite (/app/node_modules/wdio-lambdatest-service/src/service.js:103:7)
[0-1]     at async Promise.all (index 0)
[0-1]     at executeHooksWithArgs (/app/node_modules/@wdio/utils/build/index.js:867:18)
```

Im curious if this is a user error or more of something that requires support for v9.

**Comment by dnlstpnv** [comment]
+

**Comment by harsha509** [comment]
Hi @badman-rodriguez,

Thanks for reporting the issue! I tried testing it on real devices with `WDIO 9`, but I wasn’t able to reproduce it on my end.

We've also updated the `wdio-lambdatest-service` to support WDIO 9 in version `3.0.1`. Could you try updating and see if that fixes the problem? If the issue still happens, could you please share an example that reproduces it so we can investigate further?

Thanks,
Sri

**Comment by harrydevane** [comment]
We are also seeing this on WDIO v9

```
[0-0] 2024-11-15T18:19:47.748Z ERROR @wdio/utils:shim: SyntaxError: Invalid left-hand side in assignment
[0-0]     at new Function (<anonymous>)
[0-0]     at Browser.execute (file:///C:/Users/hdevane/Workspace/energy-pathfinder-supply-chain-interface/node_modules/webdriverio/build/index.js:3082:53)
[0-0]     at Browser.wrapCommandFn (file:///C:/Users/hdevane/Workspace/energy-pathfinder-supply-chain-interface/node_modules/@wdio/utils/build/index.js:884:23)
[0-0]     at LambdaRestService._executeCommand (C:\Users\hdevane\Workspace\energy-pathfinder-supply-chain-interface\node_modules\wdio-lambdatest-service\src\service.js:429:12)
[0-0]     at LambdaRestService._setSessionName (C:\Users\hdevane\Workspace\energy-pathfinder-supply-chain-interface\node_modules\wdio-lambdatest-service\src\service.js:416:5)
[0-0]     at LambdaRestService.setSessionName (C:\Users\hdevane\Workspace\energy-pathfinder-supply-chain-interface\node_modules\wdio-lambdatest-service\src\service.js:394:7)
[0-0]     at LambdaRestService.beforeSuite (C:\Users\hdevane\Workspace\energy-pathfinder-supply-chain-interface\node_modules\wdio-lambdatest-service\src\service.js:103:7)
[0-0]     at async Promise.all (index 0)
[0-0]     at executeHooksWithArgs (file:///C:/Users/hdevane/Workspace/energy-pathfinder-supply-chain-interface/node_modules/@wdio/utils/build/index.js:867:18)
```

`node_modules/webdriverio/build/index.js:3082` is the following: `const userScript = typeof script === "string" ? new Function(script) : script;`

`script` is `lambda-name=Projects page`, so it's trying to call `new Function('lambda-name=Projects page')` which causes the error

**Comment by harrydevane** [comment]
This has been solved by https://github.com/LambdaTest/wdio-lambdatest-service/pull/99
